/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OtpIndexRouteImport } from './routes/otp/index'
import { Route as MagicLinkIndexRouteImport } from './routes/magic-link/index'
import { Route as OtpVerifyRouteImport } from './routes/otp/verify'
import { Route as MagicLinkVerifyRouteImport } from './routes/magic-link/verify'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpIndexRoute = OtpIndexRouteImport.update({
  id: '/otp/',
  path: '/otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkIndexRoute = MagicLinkIndexRouteImport.update({
  id: '/magic-link/',
  path: '/magic-link/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpVerifyRoute = OtpVerifyRouteImport.update({
  id: '/otp/verify',
  path: '/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkVerifyRoute = MagicLinkVerifyRouteImport.update({
  id: '/magic-link/verify',
  path: '/magic-link/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/magic-link/verify': typeof MagicLinkVerifyRoute
  '/otp/verify': typeof OtpVerifyRoute
  '/magic-link/': typeof MagicLinkIndexRoute
  '/otp/': typeof OtpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/magic-link/verify': typeof MagicLinkVerifyRoute
  '/otp/verify': typeof OtpVerifyRoute
  '/magic-link': typeof MagicLinkIndexRoute
  '/otp': typeof OtpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/magic-link/verify': typeof MagicLinkVerifyRoute
  '/otp/verify': typeof OtpVerifyRoute
  '/magic-link/': typeof MagicLinkIndexRoute
  '/otp/': typeof OtpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/magic-link/verify'
    | '/otp/verify'
    | '/magic-link/'
    | '/otp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/magic-link/verify'
    | '/otp/verify'
    | '/magic-link'
    | '/otp'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/magic-link/verify'
    | '/otp/verify'
    | '/magic-link/'
    | '/otp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MagicLinkVerifyRoute: typeof MagicLinkVerifyRoute
  OtpVerifyRoute: typeof OtpVerifyRoute
  MagicLinkIndexRoute: typeof MagicLinkIndexRoute
  OtpIndexRoute: typeof OtpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp/': {
      id: '/otp/'
      path: '/otp'
      fullPath: '/otp/'
      preLoaderRoute: typeof OtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link/': {
      id: '/magic-link/'
      path: '/magic-link'
      fullPath: '/magic-link/'
      preLoaderRoute: typeof MagicLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp/verify': {
      id: '/otp/verify'
      path: '/otp/verify'
      fullPath: '/otp/verify'
      preLoaderRoute: typeof OtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link/verify': {
      id: '/magic-link/verify'
      path: '/magic-link/verify'
      fullPath: '/magic-link/verify'
      preLoaderRoute: typeof MagicLinkVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MagicLinkVerifyRoute: MagicLinkVerifyRoute,
  OtpVerifyRoute: OtpVerifyRoute,
  MagicLinkIndexRoute: MagicLinkIndexRoute,
  OtpIndexRoute: OtpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
