/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SessionsHistoryRouteImport } from './routes/sessions/history'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas/$ideaId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsHistoryRoute = SessionsHistoryRouteImport.update({
  id: '/sessions/history',
  path: '/sessions/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => IdeasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ideas'
    | '/inbox'
    | '/integrations'
    | '/onboarding'
    | '/ideas/$ideaId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/sessions/history'
    | '/tasks/$taskId'
    | '/projects/'
    | '/sessions/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/ideas'
    | '/inbox'
    | '/integrations'
    | '/onboarding'
    | '/ideas/$ideaId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/sessions/history'
    | '/tasks/$taskId'
    | '/projects'
    | '/sessions'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ideas'
    | '/inbox'
    | '/integrations'
    | '/onboarding'
    | '/ideas/$ideaId'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/sessions/history'
    | '/tasks/$taskId'
    | '/projects/'
    | '/sessions/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsHistoryRoute: typeof SessionsHistoryRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/history': {
      id: '/sessions/history'
      path: '/sessions/history'
      fullPath: '/sessions/history'
      preLoaderRoute: typeof SessionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof IdeasRoute
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  IdeasRoute: IdeasRouteWithChildren,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsHistoryRoute: SessionsHistoryRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
